### ISSUE TITLE
Help is not helpful

### ISSUE THREAD

**Issue by dan-zeman** [ufal/perl-pmltq-web#59]
https://lindat.mff.cuni.cz//services/pmltq/#!/treebank/hamledt_pt/help
is the target of the Help link from the Portuguese HamleDT. However, the sample queries at this page employ node attributes that come from PDT and that are not available in HamleDT or Universal Dependencies (such as `afun`).

**Comment by matyaskopp** [comment]
I don't think that I understand you. `afun` is in treex schema. Since that this treebanks can use it on a-layer.

Documentation for Hamledt_pt is generated from this [json](https://lindat.mff.cuni.cz/services/pmltq/api/treebanks/hamledt_pt):
`{...,"doc":{"type":"a-node","value":"Pred","attr":"afun","layer":"treex_document"},...}`
at the server side [PMLTQ::Server::Schema::Result::Treebank::generate_doc](https://github.com/ufal/perl-pmltq-server/blob/master/lib/PMLTQ/Server/Schema/Result/Treebank.pm#L366)

**Comment by dan-zeman** [comment]
I see. Thanks to the schema the treebank can in theory use `afun` and it even does use it in one part of the annotation but it is not the central part that I would like to use in an illustrative example. What is the current preferred way of editing the json file? I would like to modify it so that:

- it hides the node types n-node, n-root, p-nonterminal, p-terminal, t-node, t-root (not used in HamleDT)
- preferably it shows examples with the `deprel` attribute rather than `afun` (this actually also applies to all the UD treebanks, where we don't have `afun` at all — although the Treex schema is used and `afun` is in theory possible)

**Comment by matyaskopp** [comment]
now, you can write your own documentation for tag or treebank
